---
# tasks file for tinc

- name: refresh cache
  apt:
    update_cache: yes
  tags:
    - tinc_requirements
    - install

- name: install tinc
  package:
    name: tinc
    state: latest
  tags:
    - tinc_install
    - install

- name: create tinc systemd service file
  template:
    src: tinc.systemd.service.j2
    dest: /etc/systemd/system/tinc.service
  notify: Restart Service
  tags:
    - tinc_install
    - install

- include: tinc_configure.yml
  tags:
    - tinc_configure
    - configure
